### PR TITLE
Fix copy resources specs after actool arguments update

### PR DESCRIPTION
**Pull request by khomTima**
Update specs for https://github.com/CocoaPods/CocoaPods/pull/7020

### CODE REVIEW

**Comment by dnkoutso** [comment]
@khomTima I don't think this is right. I think this is updating way more files that needed. It's probably not your fault that all those files went "dirty". I expect to see only `resources.sh` files to be changed here and with only your change by this PR https://github.com/CocoaPods/CocoaPods/pull/7020

**Comment by khomTima** [comment]
@dnkoutso yes you are right :). I'll fix it soon.

**Comment by dnkoutso** [comment]
@khomTima still not looking right,  I think we only need to see `Pods-*-resources.sh` files in the diff here.

**Comment by khomTima** [comment]
@dnkoutso sorry, but otherwise the branch does not pass the tests.

**Comment by khomTima** [comment]
Specs in master last commit has the wrong version of CocoaLumberjack and libPusher

**Comment by dnkoutso** [comment]
New PR

**Pull request closed without merging**
