### PR TITLE
`execution_output.txt` updates for cocoapods/cocoapods#7882

### PR DESCRIPTION
**Pull request by jkap**
adds new log line from @dnkoutso and I

### CODE REVIEW

**Comment by jkap** [comment]
PR linked here since it did't link the title cocoapods/cocoapods#7882

**Comment by dnkoutso** [comment]
Surprised it does not include:
```
- Generating Info.plist file at ...
```

For the app host line. Is it being swallowed?

**Comment by jkap** [comment]
that's a great question. looking now

**Comment by dnkoutso** [comment]
oooh @jkap there are no app hosts for these integration specs hence there is never a plist created. We could be smarter and not output this text unless we know there are app hosts to install.

**Comment by jkap** [comment]
that makes a lot more sense and i’ll implement that change \~tomorrow\~

**Comment by jkap** [comment]
fixed it in the cocoapods PR, closing this since it's not actually necessary

**Pull request closed without merging**
