### PR TITLE
Inherit xcconfig values to the user target

### PR DESCRIPTION
**Pull request by mrackwitz**
Belongs to CocoaPods/CocoaPods#3573.

### CODE REVIEW

**Comment by segiddins** [comment]
This doesn't seem quite right to me... Isn't this xcconfig linked to both the pod target and the user target?

**Comment by mrackwitz** [comment]
This here was an issue with the framework integration specifically. Thr setting is also present in the [public pod xcconfig](https://github.com/CocoaPods/cocoapods-integration-specs/blob/master/install_custom_module_name/after/Pods/Target%20Support%20Files/Pods-libPusher/Pods-libPusher.xcconfig).

**Comment by segiddins** [comment]
In that case, won't the setting end up appearing duplicated to the pod target?

**Comment by mrackwitz** [comment]
No, the aggregate xcconfig isn't shared or inherited to pod targets and the private pod xcconfig just imports and de-namespace the public pod xcconfig.

**Comment by segiddins** [comment]
:+1: great

**Pull request merged**
