### PR TITLE
Update specs for codesign spaces fix

### PR DESCRIPTION
**Pull request by benasher44**
Specs update for CocoaPods/CocoaPods#6160

### CODE REVIEW

**Comment by segiddins** [comment]
👍

**Comment by benasher44** [comment]
@segiddins @DanToml I'm pretty confused. After CocoaPods/CocoaPods#6160 was rebased, this is the diff I see now after rebuilding integration fixtures.

**Comment by benasher44** [comment]
Master is passing, but CI from that PR confirms similar issues: https://travis-ci.org/CocoaPods/CocoaPods/builds/175946232

**Comment by segiddins** [comment]
Did you rebase this PR atop master?

**Comment by benasher44** [comment]
I did. I even branched this PR off of master again, re-built integration fixtures, and forced pushed this most recent commit. So, it should be based off of the most recent master.

**Comment by segiddins** [comment]
Did you also rebase the CocoaPods PR atop CocoaPods master, and `git submodule update`?

**Comment by benasher44** [comment]
Yep. I'll double check though and get back to you.

**Pull request merged**
